name: Lighthouse check
on: [ push ]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install & Build
        run: |
          yarn install
          yarn build
      - name: Lighthouse Check
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun
