name: ESLint
on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    branches:
      - '**'
      - '!master'

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
  check-style:
    name: Check Styles
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Check Style
        run: yarn check-style
  check-types:
    name: Check Types
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Check Types
        run: yarn check-types
