name: Website Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: install node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: yarn install
        run: yarn install
      - name: eslint
        uses: icrawl/action-eslint@v1
  build-website:
    name: Website Build
    runs-on: ubuntu-latest
    needs: eslint
    timeout-minutes: 5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Upload next-app-build
        uses: actions/upload-artifact@v2
        with:
          name: next-app-build
          path: .next
  lhci:
    name: Lighthouse check
    if: ${{ contains(github.event.pull_request.labels.*.name, 'lighthouse-check') }}
    runs-on: ubuntu-latest
    needs: build-website
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Download next-app-build
        uses: actions/download-artifact@v2
        with:
          name: next-app-build
          path: .next
      - name: install node v14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Lighthouse Check
        run: |
          npm install -g @lhci/cli@0.8.x
          npm run lighthouse-check
      - name: Upload lighthouse-check results
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-check-results
          path: |
            .lighthouseci
            !.lighthouseci/*.json
  build-storybook:
      name: Storybook Build
      runs-on: ubuntu-latest
      needs: eslint
      timeout-minutes: 5
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2
        - name: Install Dependencies
          run: yarn install
        - name: Build
          run: yarn build-storybook

