name: Website Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: eslint
        uses: icrawl/action-eslint@v1
  build-website:
    name: Website Build
    runs-on: ubuntu-latest
    needs: eslint
    timeout-minutes: 5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Build
        run: yarn build
      - name: Cache next-app-build
        uses: actions/cache@v2
        with:
          path: '.next'
          key: ${{ runner.os }}-next-${{ hashFiles('yarn.lock') }}
  lhci:
    name: Lighthouse check
    if: ${{ contains(github.event.pull_request.labels.*.name, 'lighthouse-check') }}
    runs-on: ubuntu-latest
    needs: build-website
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Cache next-app-build
        uses: actions/cache@v2
        with:
          path: '.next'
          key: ${{ runner.os }}-next-${{ hashFiles('yarn.lock') }}
      - name: Lighthouse Check
        run: |
          sudo npm install -g @lhci/cli@0.8.x
          npm run lighthouse-check
      - name: Upload lighthouse-check results
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-check-results
          path: |
            .lighthouseci
            !.lighthouseci/*.json
  build-storybook:
      name: Storybook Build
      runs-on: ubuntu-latest
      needs: eslint
      timeout-minutes: 5
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2
        - name: Cache node_modules
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
        - name: Build
          run: yarn build-storybook

