name: Build
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: master
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build